version: '2.2'

services:
  openhab:
    container_name: openhab
    image: "openhab/openhab:3.3.0"
    restart: always
    ports:
      - 8899:8080
      - 8900:5007
      - 8901:8101
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "openhab_addons:/openhab/addons"
      - ./config:/openhab/conf
      - "openhab_userdata:/openhab/userdata"
    environment:
      CRYPTO_POLICY: "unlimited"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"

    networks:
      - iot_default

  mosquitto:
    container_name: mqtt
    restart: always
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt_config:/mosquitto/config
      - ./mqtt_data:/mosquitto/data
      - ./mqtt_log:/mosquitto/log
    networks:
      - iot_default
volumes:
  openhab_addons:
    driver: local
  openhab_userdata:
    driver: local

networks: 
  iot_default:
    name: iot_default
